# Global runtime
frames=-1
fusion_window_ms=120
output_host=192.168.137.1
output_port=5000

# Camera 0
camera.0.id=cam0
camera.0.device=/dev/video0
camera.0.width=1280
camera.0.height=720
camera.0.frames=-1
camera.0.diff_threshold=25
camera.0.min_blob_area=120
camera.0.x=0.0
camera.0.y=0.0
camera.0.z=1.5
camera.0.yaw_deg=0.0
camera.0.pitch_deg=90.0
camera.0.roll_deg=0.0
camera.0.fov_deg=65.0
camera.0.enabled=true

# Camera 1
camera.1.id=cam1
camera.1.device=/dev/video1
camera.1.width=1280
camera.1.height=720
camera.1.frames=-1
camera.1.diff_threshold=25
camera.1.min_blob_area=120
camera.1.x=0.6
camera.1.y=0.0
camera.1.z=1.5
camera.1.yaw_deg=12.0
camera.1.pitch_deg=90.0
camera.1.roll_deg=0.0
camera.1.fov_deg=65.0
camera.1.enabled=false
