# Global runtime
frames=-1
fusion_window_ms=120
output_host=192.168.137.1

output_port=5000
# Optional GPS origin for demo mode
reference_lat=48.82603
reference_lon=2.36605
reference_alt=35.0

# Camera 0
camera.0.id=cam0
camera.0.device=http://admin:admin@192.168.137.160:8081/video
camera.0.width=1280
camera.0.height=720
camera.0.frames=-1
camera.0.diff_threshold=25
camera.0.min_blob_area=120
camera.0.fov_deg=65.0
camera.0.enabled=true
# Optional GPS demo values
camera.0.gps_lat=48.82603
camera.0.gps_lon=2.36605
camera.0.gps_alt=35.0
camera.0.heading_deg=340.0

# Camera 1
camera.1.id=cam1
camera.1.device=http://admin:admin@192.168.137.173:8081/video
camera.1.width=1280
camera.1.height=720
camera.1.frames=-1
camera.1.diff_threshold=25
camera.1.min_blob_area=120
camera.1.fov_deg=65.0
camera.1.enabled=true
# Optional GPS demo values
camera.1.gps_lat=48.82608
camera.1.gps_lon=2.36596
camera.1.gps_alt=35.0
camera.1.heading_deg=164.0
